const dotenv = require("dotenv");
dotenv.config();

const {
  PORT,
  MONGO_URL,
  FRONTEND_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_AUTH_STATE,
  GOOGLE_AUTH_SCOPE,
  GOOGLE_AUTH_BASE_URL,
  SECRET: SECRET_KEY,
  GOOGLE_AUTH_CLIENT_SECRET: GOOGLE_CLIENT_SECRET,
  GOOGLE_AUTH_REDIRECT_URI: GOOGLE_REDIRECT_URI,
} = process.env;

module.exports = {
  MONGO_URL,
  SECRET_KEY,
  PORT,
  FRONTEND_URL,
  GOOGLE_CLIENT_ID,
  GOOGLE_CLIENT_SECRET,
  GOOGLE_REDIRECT_URI,
  GOOGLE_AUTH_PROMPT_URL: `${GOOGLE_AUTH_BASE_URL}?client_id=${GOOGLE_CLIENT_ID}&redirect_uri=${GOOGLE_REDIRECT_URI}&response_type=code&scope=${GOOGLE_AUTH_SCOPE}&state=${GOOGLE_AUTH_STATE}&prompt=consent`,
};
